[package]
name = "backend"
authors = ["hikoir"]
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["full"] }
twitch_api = { version = "0.7.2", features = ["helix", "eventsub", "reqwest"] }
